### ISSUE TITLE
how to fix this error when I try example code.

### ISSUE THREAD

**Issue by nongtee7559** [Afonsocraposo/buttons_tabbar#8] opened 2020-11-02 05:33 UTC
dependOnInheritedWidgetOfExactType<_TabControllerScope>() or dependOnInheritedElement() was called before _ButtonsTabBarState.initState() completed.
![image](https://user-images.githubusercontent.com/50226242/97833195-67e57680-1d07-11eb-917d-aa4e22e82edc.png)

**Comment by Silfalion** [comment] 2020-11-24 17:31
have the same issue, any fix?

**Comment by Afonsocraposo** [comment] 2020-11-25 10:06
@Silfalion  can you provide the minimal code to reproduce this error and also the complete error log its returning?
@nongtee7559 since you closed this issue, did you find the solution to the problem?

**Comment by Silfalion** [comment] 2020-11-26 20:22
Hi @Afonsocraposo, used the example provided on pub.dev. Will send the precise file I used in on tomorrow.

**Comment by DungNgo96** [comment] 2020-11-30 02:11
You can initialize a new TabController and remove the DefaultTabController()

    class _ExampleState extends State<Example> with SingleTickerProviderStateMixin {
      TabController _tabController;
      @override
      void initState() {
        _tabController = new TabController(length: 6, vsync: this);
        super.initState();
      }

      @override
      Widget build(BuildContext context) {
        return 
          ....
          ButtonsTabBar(
            controller _tabController;
          )

          ....
          TabBarView(
            controller _tabController;
          )
      }
    }

**Comment by Afonsocraposo** [comment] 2020-11-30 15:34
@DungNgo96 thank you for your input.

@Silfalion and @nongtee7559 I found the problem and fixed it. The default example is working now.
Update your `pubspec.yaml` to use the fixed version:
```yaml
buttons_tabbar: ^1.0.2+1
```

**Closed by Afonsocraposo** 2020-11-30 15:34 UTC
